repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [ --format, parsable, --strict ]
        exclude_types:
          - yaml
        exclude: '(_base|locale|.*/migrations)/|(?!.*apps\.py).*'
        types: [ yaml ]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.12
        additional_dependencies: [ "click~=8.1" ]
        types: [ python ]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        language_version: python3.12
        exclude: '(_base|locale|.*/migrations)/|(?!.*apps\.py).*'
        types: [ python ]
        args: ['--max-line-length=100']
